name = "glistix_json"
version = "1.0.0"
gleam = ">= 0.32.0"

licences = ["Apache-2.0"]
description = "Work with JSON in Glistix - Port of gleam_json to Nix"

repository = { type = "github", user = "glistix", repo = "json" }
links = []

[dependencies]
gleam_stdlib = "~> 0.19 or ~> 1.0"
thoas = "~> 0.2"

[dev-dependencies]
glistix_gleeunit = ">= 1.0.0 and < 2.0.0"

# Use glistix_stdlib when running
[glistix.preview.patch]
gleam_stdlib = { name = "glistix_stdlib", version = "~> 0.19 or ~> 1.0" }
