name = "gleam_json"
version = "1.0.0"
gleam = ">= 0.32.0"

licences = ["Apache-2.0"]
description = "Work with JSON in Glistix - Port of gleam_json to Nix"

repository = { type = "github", user = "glistix", repo = "json" }
links = []

[dependencies]
# Run 'git submodule add --name stdlib -- https://github.com/glistix/stdlib external/stdlib'
# to clone Glistix's stdlib patch to the local path specified below. This is needed so stdlib
# will work on the Nix target. Hex dependents will use the stdlib version specified below,
# in [glistix.preview.hex-patch], instead.
gleam_stdlib = { path = "./external/stdlib" }
thoas = "~> 0.2"

[dev-dependencies]
glistix_gleeunit = ">= 1.0.0 and < 2.0.0"

# The [glistix.preview] namespace contains useful settings which will be needed
# during Glistix beta. In the future, it's likely these won't be necessary
# anymore.
[glistix.preview]
# If you're patching a package using a local dependency/Git submodule and you
# get a local dependency conflict error, add it to the list below.
local-overrides = ["gleam_stdlib"]

# The section below allows publishing your package to Hex despite having
# local dependencies, by declaring that you depend on another Hex package
# instead.
# This is needed to be able to patch stdlib etc. locally during development
# and at the same time publish to Hex without the patch.
# The section below should only be used for this purpose. Please do not abuse
# this feature, as it is mostly a temporary workaround while Gleam doesn't have
# a proper dependency patching system.
[glistix.preview.hex-patch]
gleam_stdlib = "~> 0.19 or ~> 1.0"
